{% set version = "1.10.1.post20200504175005" %}

package:
  name: cloud_sptheme
  version: {{ version }}

source:
  fn: cloud_sptheme-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/c/cloud_sptheme/cloud_sptheme-{{ version }}.tar.gz
  sha256: caf47ac4c6346eef47fc11e799adbeaf645921c712cc099cf2530560e7ecde44
  patches:
    - 0001-patch-sphinx-4-support.patch
    - 0002-patch-jinja-markup-deprecation.patch
    - 0003-fix-pycompat-warning.patch
    - 0004-fix-docutils-0.17-issues-with-toggle-html.patch

build:
  noarch: python
  number: 4
  preserve_egg_dir: true
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - sphinx >=1.6
    - markupsafe
    - jinja2

test:
  requires:
    - python {{ python_min }}
  imports:
    - cloud_sptheme
    - cloud_sptheme.ext

about:
  home: https://cloud-sptheme.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A nice sphinx theme named 'Cloud', and some related extensions.

extra:
  recipe-maintainers:
    - melund
    - jakirkham
