{% set version = "1.10.0" %}

package:
  name: cloud_sptheme
  version: {{ version }}

source:
  fn: cloud_sptheme-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/cloud_sptheme/cloud_sptheme-{{ version }}.tar.gz
  sha256: e55448c14087a7fcbba7d58d6d9edf12190b73ea9c1ca68562ca75aeabbe484a

build:
  noarch: python
  number: 0
  preserve_egg_dir: True
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - sphinx >=1.6

test:
  imports:
    - cloud_sptheme
    - cloud_sptheme.ext

about:
  home: https://bitbucket.org/ecollins/cloud_sptheme
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A nice sphinx theme named 'Cloud', and some related extensions.

extra:
  recipe-maintainers:
    - jakirkham
