travis:
  secure:
    BINSTAR_TOKEN: FFXCSQl0pkaimQBt66C739iW9/wv5Li+UgVaVi4+vS2V22VeOt9qW29rELpPKjF0+/Az53x37UtX7zLAtBPhUmichloCxczHebtcI0qweOZi6vyBaTWr6upQ2K5UAhHVhVoQ8XbtoZei7ojH1mQfKTfdA1YiuV24zgFoH1cBzAdGWXcf+ke0V6OabXfen6AuU5bh1WZvDIlRH5CjTan6kAsWeUuweLRAeqcvM4WFI0W0SZRvDB0PWx2OQqLwksJZc/soKd6HZZ2Yt61TJcSZERgYLh66paVmdJQntAU8TroDvOq+HU1HTQAVnkR43djXI+5Ozd+Lq/FTZVrCEe+OyAvAfQG4ZzX5evSRSBkG23ATaYlBQ6m8xy2BlaThl5nLI65d5Jsj9yNd82b6WWHJpuixw9SSmOKl4eagsp4Frzbso/VnIUER3YHQ4JSDueLfxBLqc0WyetjO1HpmQv8RmG4r+UPg8cmtaM7fycNPY2QwbPkVjWrxggwuAhRLo1sbVWcTNKqUD2t9lBtr4pgYUrlUbqK+p6y25HTz1diQIeb/TAcfjKwntl/Mzq9H4rRF19xLAF4nhtCCrY2PgzNNUKIQ5R5RP75GkNFRIreoMYh4zLsISzlwU7x005Ei9bk+i5Zf2T/1LMsBgZNm5fY+0O3JK3wScWlEIekIatMTy14=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
