travis:
  secure:
    BINSTAR_TOKEN: Z1UMOQahBrhS8WY9pgnl+Sy+87I64EDeGsLoh/qPi3gDNoLOtMMx8rm7R87lB9gDw6c9v28y/DYt6OweXXMa3JwX8yxmZyJSIrgIZ473i3bRWGCvpgkcOQt0ldW5k/QXAOj8qS6a5xsMRTL9qxE1wd1IFB92w/2Yb6VrLOqJUV11+MZTIMIo+5B/VSbNmWmq4jVrJLNzoB8qLtcqHSlSPx79zgx/gV+6uZpRi1aJvxnCWx8zlfVjnY7aR2iJjQ18Newr2cgQKGXTBnEeIVuGdX2yr1tOKswp/xAK9zcKW+sxviEIprTDZaaxtmh7uzRWKrE3wcrV8Bn/xVurVAldcO4IGJ6OF4I5vdvueOCQYJBSoeWcwtfFEgVEtL/0EVFiOnQxRUtV65ewpLOQ+hRq9aFBPwIh8WQ5RhDe1S9K3PT51e/PL5l7fPPB5T5jQ76ttiuT+Kytg1/sSIM4WnqIUm0lhkjvjuZ91u5co1YF/DgiagKm27B0dFLFS4k8GBrjRZzmMqutqAHOPVADZkntmivEaQoKyu80JcQ5sALtM1h0eBZWCjnLLWoxPsmhzW4gz/Wxje+JTcl14Wo4qdQNqtK/1syGHjuBJOcJhGCGTNz/g4jm/Sy78Xjrw3d91u6FaMPFakln4EqK8ur5WX3yhr5JPMB4xV8G3D3e2zyjrA0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
